### ISSUE TITLE
cannot work

### ISSUE THREAD

**Issue by SuperManHa** [peace195/aspect-based-sentiment-analysis#2]
Environment：
python 2.7.13 （Anaconda）
tensorflow0.12.1
and I got this error:

Traceback (most recent call last):
  File "/root/PycharmProjects/aspect-based-sentiment-analysis/code/sa_aspect_oop.py", line 392, in <module>
    main()
  File "/root/PycharmProjects/aspect-based-sentiment-analysis/code/sa_aspect_oop.py", line 383, in main
    model.modeling()
  File "/root/PycharmProjects/aspect-based-sentiment-analysis/code/sa_aspect_oop.py", line 146, in modeling
    **X_train = tf.concat([self.tf_X_train, X_sent_for_word], 2)**
  File "/root/.pyenv/versions/anaconda2-5.0.0/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1075, in concat
    dtype=dtypes.int32).get_shape(
  File "/root/.pyenv/versions/anaconda2-5.0.0/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/root/.pyenv/versions/anaconda2-5.0.0/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/root/.pyenv/versions/anaconda2-5.0.0/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/root/.pyenv/versions/anaconda2-5.0.0/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/root/.pyenv/versions/anaconda2-5.0.0/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
**TypeError: Expected int32, got list containing Tensors of type '_Message' instead.**

Should I change the version of TensorFlow? THANKS

**Comment by SuperManHa** [comment]
The reason is the version of tensorflow.

maybe you can modify README.md which links to tensorflow 0.12 (not tensorflow 1.2)

**Comment by peace195** [comment]
Thank you. I updated it.

**Comment by hnstr** [comment]
The code works for me with small modifications with python 3 and tensorflow 1.2.1:

change in `utils.py`
- line 30 remove `continue`
- line 65 `.iteritems()` to `.items()`

**Comment by peace195** [comment]
@hnstr Thank you very much. Would you mind voting me a “star" for this project. I am happy for that :).
