### ISSUE TITLE
SyntaxError: 'continue' not properly in loop

### ISSUE THREAD

**Issue by SeekPoint** [peace195/aspect-based-sentiment-analysis#6]
mldl@ub1604:~/ub16_prj/aspect-based-sentiment-analysis/code$ python sa_aspect_oop.py 
Traceback (most recent call last):
  File "sa_aspect_oop.py", line 15, in <module>
    import utils
  File "/home/mldl/ub16_prj/aspect-based-sentiment-analysis/code/utils.py", line 30
    continue
SyntaxError: 'continue' not properly in loop
mldl@ub1604:~/ub16_prj/aspect-based-sentiment-analysis/code$

**Comment by SeekPoint** [comment]
just pass it
