### ISSUE TITLE
this link is not available , it report in the trash folder of owner, must be restore by owner

### ISSUE THREAD

**Issue by SeekPoint** [peace195/aspect-based-sentiment-analysis#7]
https://drive.google.com/drive/folders/0B7O__AeIXgEkRjdLenQ5Ynl4aFk?usp=sharing

**Comment by SeekPoint** [comment]
I guess it can fix:

ub16hp@UB16HP:~/ub16_prj/__ABSA__/aspect-based-sentiment-analysis/code$ python sa_aspect_oop.py
2018-10-27 00:26:27.755886: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-10-27 00:26:27.824259: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-10-27 00:26:27.824636: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 950M major: 5 minor: 0 memoryClockRate(GHz): 1.124
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 3.52GiB
2018-10-27 00:26:27.824670: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Traceback (most recent call last):
  File "sa_aspect_oop.py", line 392, in <module>
    main()
  File "sa_aspect_oop.py", line 374, in main
    flag_change_file_structure, negative_weight, positive_weight, neutral_weight, flag_use_sentiment_embedding)
  File "sa_aspect_oop.py", line 49, in __init__
    self.flag_use_sentiment_embedding
  File "/home/ub16hp/ub16_prj/aspect-based-sentiment-analysis/code/utils.py", line 626, in load_data
    word_dict, word_dict_rev, embedding = load_embedding(domain, data_dir, flag_addition_corpus, flag_word2vec, flag_use_sentiment_embedding)
  File "/home/ub16hp/ub16_prj/aspect-based-sentiment-analysis/code/utils.py", line 45, in load_embedding
    f_vec = codecs.open('../data/' + domain + '_cbow_final_2014.vec', 'r', 'utf-8')
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: '../data/Restaurants_cbow_final_2014.vec'

**Comment by peace195** [comment]
Hope it helps!

https://drive.google.com/open?id=13zxV0gGuo-KjZoEJ4wYHhfsdkGHH1875
https://drive.google.com/open?id=1mmah5J0cypEA6aaaLKvIHrSHHACGH3cm
https://drive.google.com/open?id=1jOVif_wL2M1_UIPleMuyHrHGqK-nVij2
